**Series:** It is defined as a one dimensional array that is capable of storing various data types

In [83]:
import pandas as pd
x = [1,2,3,4,5]
a = pd.Series(x,index=['a','b','c','d','e'],dtype = float)#index used to chnge the index
print(a) #dtype used to change the data type
print(type(a))#returns type of the value
print(a[1])#to get value

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64
<class 'pandas.core.series.Series'>
2.0

/tmp/ipykernel_1024/1260751754.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(a[1])#to get value

In [84]:
dic = {"name":['python','c','c++','java'],"pop":[12,13,14,15],"rank":[1,4,3,2]}
var1 = pd.Series(dic)
print(var1)

name    [python, c, c++, java]
pop           [12, 13, 14, 15]
rank              [1, 4, 3, 2]
dtype: object

In [85]:
s1 = pd.Series(12,index=[1,2,3,4,5])
print(s1)
print(type(s1))

1    12
2    12
3    12
4    12
5    12
dtype: int64
<class 'pandas.core.series.Series'>

In [86]:
s2 = pd.Series(12,index=[1,2,3])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4     NaN
5     NaN
dtype: float64

**DataFrame**

In [87]:
x=[1,2,3,4,5]

var = pd.DataFrame(x)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>

In [88]:
var1 = pd.DataFrame(dic)
print(var1)

     name  pop  rank
0  python   12     1
1       c   13     4
2     c++   14     3
3    java   15     2

In [89]:
var2 = pd.DataFrame(dic,columns=['pop','name']) #to get specified coloumns
print(var2)

   pop    name
0   12  python
1   13       c
2   14     c++
3   15    java

In [90]:
print(var1['name'][3])

java

In [91]:
list1=[[1,2,3,4,5],[11,12,13,14,15]]
var3 = pd.DataFrame(list1)
print(var3)

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [92]:
sr = {"s": pd.Series([1,2,3,4]),"r":pd.Series([11,12,13,14])}
var4 = pd.DataFrame(sr)
print(var4)

   s   r
0  1  11
1  2  12
2  3  13
3  4  14

**Arithmetic Operations**

In [93]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [94]:
var["C"] = var["A"] + var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [95]:
var["C"] = var["A"] - var["B"]
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [96]:
var["C"] = var["A"] * var["B"]
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [97]:
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[15,16,17,18]})
var1

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

In [98]:
var1["Python"] = var1["A"] <= 20
var1['python_1'] = var1["B"] >= 16
var1

    A   B  Python  python_1
0  10  15    True     False
1  20  16    True      True
2  30  17   False      True
3  40  18   False      True

**Insert**

In [99]:
var6 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var6

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [100]:
var6.insert(1,'C',var6['A'])
var6

   A  C  B
0  1  1  5
1  2  2  6
2  3  3  7
3  4  4  8

In [101]:
var6.insert(1,'E',[11,12,13,14])
var6

   A   E  C  B
0  1  11  1  5
1  2  12  2  6
2  3  13  3  7
3  4  14  4  8

In [102]:
var6['P'] = var6['A'][:3]
var6

   A   E  C  B    P
0  1  11  1  5  1.0
1  2  12  2  6  2.0
2  3  13  3  7  3.0
3  4  14  4  8  NaN

**Delete**

In [103]:
var6.pop('E')
var6

   A  C  B    P
0  1  1  5  1.0
1  2  2  6  2.0
2  3  3  7  3.0
3  4  4  8  NaN

In [104]:
del var6['P']
var6

   A  C  B
0  1  1  5
1  2  2  6
2  3  3  7
3  4  4  8

**CSV Files :** is a plain text format in which values are aeperated by commas (Comma Seperated Values)

In [105]:
dis = {"a":[1,2,3,4,5,6],"s":[7,8,9,10,11,12],"d":[13,14,15,16,17,18]}
d = pd.DataFrame(dis)
d.to_csv("Test_new.csv",index=False,header = [1,2,3])

In [106]:
csv_1 = pd.read_csv("Iris.csv")
csv_1

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [107]:
csv_2 = pd.read_csv("Iris.csv",nrows = 10)
csv_2

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [108]:
csv_3 = pd.read_csv("Iris.csv",usecols=["SepalLengthCm","SepalWidthCm"])
csv_3

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [109]:
csv_4 = pd.read_csv("Iris.csv",skiprows=[1])
csv_4 #to skip rows

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,2,4.9,3.0,1.4,0.2,Iris-setosa
1,3,4.7,3.2,1.3,0.2,Iris-setosa
2,4,4.6,3.1,1.5,0.2,Iris-setosa
3,5,5.0,3.6,1.4,0.2,Iris-setosa
4,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
144,146,6.7,3.0,5.2,2.3,Iris-virginica
145,147,6.3,2.5,5.0,1.9,Iris-virginica
146,148,6.5,3.0,5.2,2.0,Iris-virginica
147,149,6.2,3.4,5.4,2.3,Iris-virginica
148,150,5.9,3.0,5.1,1.8,Iris-virginica

In [110]:
csv_5 = pd.read_csv("Iris.csv",index_col="Species")
csv_5 #to change index coloumn

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa       1            5.1           3.5            1.4           0.2
Iris-setosa       2            4.9           3.0            1.4           0.2
Iris-setosa       3            4.7           3.2            1.3           0.2
Iris-setosa       4            4.6           3.1            1.5           0.2
Iris-setosa       5            5.0           3.6            1.4           0.2
...             ...            ...           ...            ...           ...
Iris-virginica  146            6.7           3.0            5.2           2.3
Iris-virginica  147            6.3           2.5            5.0           1.9
Iris-virginica  148            6.5           3.0            5.2           2.0
Iris-virginica  149            6.2           3.4            5.4           2.3
Iris-virginica  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [111]:
csv_6 = pd.read_csv("Iris.csv",header = 3)
csv_6 #change heading
#names can be used to change the heading names

       3  4.7  3.2  1.3  0.2     Iris-setosa
0      4  4.6  3.1  1.5  0.2     Iris-setosa
1      5  5.0  3.6  1.4  0.2     Iris-setosa
2      6  5.4  3.9  1.7  0.4     Iris-setosa
3      7  4.6  3.4  1.4  0.3     Iris-setosa
4      8  5.0  3.4  1.5  0.2     Iris-setosa
..   ...  ...  ...  ...  ...             ...
142  146  6.7  3.0  5.2  2.3  Iris-virginica
143  147  6.3  2.5  5.0  1.9  Iris-virginica
144  148  6.5  3.0  5.2  2.0  Iris-virginica
145  149  6.2  3.4  5.4  2.3  Iris-virginica
146  150  5.9  3.0  5.1  1.8  Iris-virginica

[147 rows x 6 columns]

In [112]:
csv_7 = pd.read_csv("Iris.csv",header = None)
csv_7 #to remove header name

,0,1,2,3,4,5
0,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,1,5.1,3.5,1.4,0.2,Iris-setosa
2,2,4.9,3.0,1.4,0.2,Iris-setosa
3,3,4.7,3.2,1.3,0.2,Iris-setosa
4,4,4.6,3.1,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
146,146,6.7,3.0,5.2,2.3,Iris-virginica
147,147,6.3,2.5,5.0,1.9,Iris-virginica
148,148,6.5,3.0,5.2,2.0,Iris-virginica
149,149,6.2,3.4,5.4,2.3,Iris-virginica
150,150,5.9,3.0,5.1,1.8,Iris-virginica

**Pandas Function**

In [113]:
csv1 = pd.read_csv("Iris.csv")
csv1

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [114]:
csv1.index

RangeIndex(start=0, stop=150, step=1)

In [115]:
csv1.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [116]:
csv1.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [117]:
csv1.head(2) #returns top values

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [118]:
csv1.tail(2) #returns last value

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [119]:
csv1[:50]

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [120]:
print(type(csv1))

<class 'pandas.core.frame.DataFrame'>

In [121]:
csv1.index.array

<NumpyExtensionArray>
[  np.int64(0),   np.int64(1),   np.int64(2),   np.int64(3),   np.int64(4),
   np.int64(5),   np.int64(6),   np.int64(7),   np.int64(8),   np.int64(9),
 ...
 np.int64(140), np.int64(141), np.int64(142), np.int64(143), np.int64(144),
 np.int64(145), np.int64(146), np.int64(147), np.int64(148), np.int64(149)]
Length: 150, dtype: int64

In [122]:
csv1.to_numpy()

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
       [25, 4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [26, 5.0, 3.0, 1.6, 0.2, 'Iris-setosa'],
       [27, 5.0, 3.4, 1.6, 0.4, 'Iris-setosa'],
       [28, 5.2, 3.5, 1.5, 0.2, 'Iris-setosa'],
       [29, 5.2, 3.4, 1.4, 0.2, 'Iris-setosa'],
       [30, 4.7, 3.2, 1.6, 0.2, 'Iris-setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [32, 5.4, 3.4, 1.5, 0.4, 'Iris-setosa'],
       [33, 5.2, 4.1, 1.5, 0.1, 'Iris-setosa'],
       [34, 5.5, 4.2, 1.4, 0.2, 'Iris-setosa'],
       [35, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [36, 5.0, 3.2, 1.2, 0.2, 'Iris-setosa'],
       [37, 5.5, 3.5, 1.3, 0.2, 'Iris-setosa'],
       [38, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [39, 4.4, 3.0, 1.3, 0.2, 'Iris-setosa'],
       [40, 5.1, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [41, 5.0, 3.5, 1.3, 0.3, 'Iris-setosa'],
       [42, 4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [43, 4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [44, 5.0, 3.5, 1.6, 0.6, 'Iris-setosa'],
       [45, 5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [46, 4.8, 3.0, 1.4, 0.3, 'Iris-setosa'],
       [47, 5.1, 3.8, 1.6, 0.2, 'Iris-setosa'],
       [48, 4.6, 3.2, 1.4, 0.2, 'Iris-setosa'],
       [49, 5.3, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [50, 5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [51, 7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'],
       [52, 6.4, 3.2, 4.5, 1.5, 'Iris-versicolor'],
       [53, 6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'],
       [54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'],
       [55, 6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'],
       [56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'],
       [57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'],
       [58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [59, 6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'],
       [60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'],
       [61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'],
       [62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'],
       [63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [64, 6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'],
       [65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'],
       [66, 6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'],
       [67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'],
       [69, 6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'],
       [70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'],
       [71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'],
       [72, 6.1, 2.8, 4.0, 1.3, 'Iris-versicolor'],
       [73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'],
       [74, 6.1, 2.8, 4.7, 1.2, 'Iris-versicolor'],
       [75, 6.4, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [76, 6.6, 3.0, 4.4, 1.4, 'Iris-versicolor'],
       [77, 6.8, 2.8, 4.8, 1.4, 'Iris-versicolor'],
       [78, 6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'],
       [80, 5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'],
       [81, 5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'],
       [82, 5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'],
       [83, 5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'],
       [84, 6.0, 2.7, 5.1, 1.6, 'Iris-versicolor'],
       [85, 5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [86, 6.0, 3.4, 4.5, 1.6, 'Iris-versicolor'],
       [87, 6.7, 3.1, 4.7, 1.5, 'Iris-versicolor'],
       [88, 6.3, 2.3, 4.4, 1.3, 'Iris-versicolor'],
       [89, 5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'],
       [90, 5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'],
       [91, 5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'],
       [92, 6.1, 3.0, 4.6, 1.4, 'Iris-versicolor'],
       [93, 5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'],
       [94, 5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'],
       [95, 5.6, 2.7, 4.2, 1.3, 'Iris-versicolor'],
       [96, 5.7, 3.0, 4.2, 1.2, 'Iris-versicolor'],
       [97, 5.7, 2.9, 4.2, 1.3, 'Iris-versicolor'],
       [98, 6.2, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [99, 5.1, 2.5, 3.0, 1.1, 'Iris-versicolor'],
       [100, 5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'],
       [101, 6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [102, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [103, 7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [104, 6.3, 2.9, 5.6, 1.8, 'Iris-virginica'],
       [105, 6.5, 3.0, 5.8, 2.2, 'Iris-virginica'],
       [106, 7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [107, 4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [108, 7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [109, 6.7, 2.5, 5.8, 1.8, 'Iris-virginica'],
       [110, 7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [111, 6.5, 3.2, 5.1, 2.0, 'Iris-virginica'],
       [112, 6.4, 2.7, 5.3, 1.9, 'Iris-virginica'],
       [113, 6.8, 3.0, 5.5, 2.1, 'Iris-virginica'],
       [114, 5.7, 2.5, 5.0, 2.0, 'Iris-virginica'],
       [115, 5.8, 2.8, 5.1, 2.4, 'Iris-virginica'],
       [116, 6.4, 3.2, 5.3, 2.3, 'Iris-virginica'],
       [117, 6.5, 3.0, 5.5, 1.8, 'Iris-virginica'],
       [118, 7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [119, 7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [120, 6.0, 2.2, 5.0, 1.5, 'Iris-virginica'],
       [121, 6.9, 3.2, 5.7, 2.3, 'Iris-virginica'],
       [122, 5.6, 2.8, 4.9, 2.0, 'Iris-virginica'],
       [123, 7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [124, 6.3, 2.7, 4.9, 1.8, 'Iris-virginica'],
       [125, 6.7, 3.3, 5.7, 2.1, 'Iris-virginica'],
       [126, 7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [127, 6.2, 2.8, 4.8, 1.8, 'Iris-virginica'],
       [128, 6.1, 3.0, 4.9, 1.8, 'Iris-virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [130, 7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [131, 7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [132, 7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [133, 6.4, 2.8, 5.6, 2.2, 'Iris-virginica'],
       [134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'],
       [135, 6.1, 2.6, 5.6, 1.4, 'Iris-virginica'],
       [136, 7.7, 3.0, 6.1, 2.3, 'Iris-virginica'],
       [137, 6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [138, 6.4, 3.1, 5.5, 1.8, 'Iris-virginica'],
       [139, 6.0, 3.0, 4.8, 1.8, 'Iris-virginica'],
       [140, 6.9, 3.1, 5.4, 2.1, 'Iris-virginica'],
       [141, 6.7, 3.1, 5.6, 2.4, 'Iris-virginica'],
       [142, 6.9, 3.1, 5.1, 2.3, 'Iris-virginica'],
       [143, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [144, 6.8, 3.2, 5.9, 2.3, 'Iris-virginica'],
       [145, 6.7, 3.3, 5.7, 2.5, 'Iris-virginica'],
       [146, 6.7, 3.0, 5.2, 2.3, 'Iris-virginica'],
       [147, 6.3, 2.5, 5.0, 1.9, 'Iris-virginica'],
       [148, 6.5, 3.0, 5.2, 2.0, 'Iris-virginica'],
       [149, 6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [150, 5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)

In [123]:
import numpy as np
v = np.asarray(csv1)
v

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
       [25, 4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [26, 5.0, 3.0, 1.6, 0.2, 'Iris-setosa'],
       [27, 5.0, 3.4, 1.6, 0.4, 'Iris-setosa'],
       [28, 5.2, 3.5, 1.5, 0.2, 'Iris-setosa'],
       [29, 5.2, 3.4, 1.4, 0.2, 'Iris-setosa'],
       [30, 4.7, 3.2, 1.6, 0.2, 'Iris-setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [32, 5.4, 3.4, 1.5, 0.4, 'Iris-setosa'],
       [33, 5.2, 4.1, 1.5, 0.1, 'Iris-setosa'],
       [34, 5.5, 4.2, 1.4, 0.2, 'Iris-setosa'],
       [35, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [36, 5.0, 3.2, 1.2, 0.2, 'Iris-setosa'],
       [37, 5.5, 3.5, 1.3, 0.2, 'Iris-setosa'],
       [38, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [39, 4.4, 3.0, 1.3, 0.2, 'Iris-setosa'],
       [40, 5.1, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [41, 5.0, 3.5, 1.3, 0.3, 'Iris-setosa'],
       [42, 4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [43, 4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [44, 5.0, 3.5, 1.6, 0.6, 'Iris-setosa'],
       [45, 5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [46, 4.8, 3.0, 1.4, 0.3, 'Iris-setosa'],
       [47, 5.1, 3.8, 1.6, 0.2, 'Iris-setosa'],
       [48, 4.6, 3.2, 1.4, 0.2, 'Iris-setosa'],
       [49, 5.3, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [50, 5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [51, 7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'],
       [52, 6.4, 3.2, 4.5, 1.5, 'Iris-versicolor'],
       [53, 6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'],
       [54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'],
       [55, 6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'],
       [56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'],
       [57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'],
       [58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [59, 6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'],
       [60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'],
       [61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'],
       [62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'],
       [63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [64, 6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'],
       [65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'],
       [66, 6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'],
       [67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'],
       [69, 6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'],
       [70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'],
       [71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'],
       [72, 6.1, 2.8, 4.0, 1.3, 'Iris-versicolor'],
       [73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'],
       [74, 6.1, 2.8, 4.7, 1.2, 'Iris-versicolor'],
       [75, 6.4, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [76, 6.6, 3.0, 4.4, 1.4, 'Iris-versicolor'],
       [77, 6.8, 2.8, 4.8, 1.4, 'Iris-versicolor'],
       [78, 6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'],
       [80, 5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'],
       [81, 5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'],
       [82, 5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'],
       [83, 5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'],
       [84, 6.0, 2.7, 5.1, 1.6, 'Iris-versicolor'],
       [85, 5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [86, 6.0, 3.4, 4.5, 1.6, 'Iris-versicolor'],
       [87, 6.7, 3.1, 4.7, 1.5, 'Iris-versicolor'],
       [88, 6.3, 2.3, 4.4, 1.3, 'Iris-versicolor'],
       [89, 5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'],
       [90, 5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'],
       [91, 5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'],
       [92, 6.1, 3.0, 4.6, 1.4, 'Iris-versicolor'],
       [93, 5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'],
       [94, 5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'],
       [95, 5.6, 2.7, 4.2, 1.3, 'Iris-versicolor'],
       [96, 5.7, 3.0, 4.2, 1.2, 'Iris-versicolor'],
       [97, 5.7, 2.9, 4.2, 1.3, 'Iris-versicolor'],
       [98, 6.2, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [99, 5.1, 2.5, 3.0, 1.1, 'Iris-versicolor'],
       [100, 5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'],
       [101, 6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [102, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [103, 7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [104, 6.3, 2.9, 5.6, 1.8, 'Iris-virginica'],
       [105, 6.5, 3.0, 5.8, 2.2, 'Iris-virginica'],
       [106, 7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [107, 4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [108, 7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [109, 6.7, 2.5, 5.8, 1.8, 'Iris-virginica'],
       [110, 7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [111, 6.5, 3.2, 5.1, 2.0, 'Iris-virginica'],
       [112, 6.4, 2.7, 5.3, 1.9, 'Iris-virginica'],
       [113, 6.8, 3.0, 5.5, 2.1, 'Iris-virginica'],
       [114, 5.7, 2.5, 5.0, 2.0, 'Iris-virginica'],
       [115, 5.8, 2.8, 5.1, 2.4, 'Iris-virginica'],
       [116, 6.4, 3.2, 5.3, 2.3, 'Iris-virginica'],
       [117, 6.5, 3.0, 5.5, 1.8, 'Iris-virginica'],
       [118, 7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [119, 7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [120, 6.0, 2.2, 5.0, 1.5, 'Iris-virginica'],
       [121, 6.9, 3.2, 5.7, 2.3, 'Iris-virginica'],
       [122, 5.6, 2.8, 4.9, 2.0, 'Iris-virginica'],
       [123, 7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [124, 6.3, 2.7, 4.9, 1.8, 'Iris-virginica'],
       [125, 6.7, 3.3, 5.7, 2.1, 'Iris-virginica'],
       [126, 7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [127, 6.2, 2.8, 4.8, 1.8, 'Iris-virginica'],
       [128, 6.1, 3.0, 4.9, 1.8, 'Iris-virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [130, 7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [131, 7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [132, 7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [133, 6.4, 2.8, 5.6, 2.2, 'Iris-virginica'],
       [134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'],
       [135, 6.1, 2.6, 5.6, 1.4, 'Iris-virginica'],
       [136, 7.7, 3.0, 6.1, 2.3, 'Iris-virginica'],
       [137, 6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [138, 6.4, 3.1, 5.5, 1.8, 'Iris-virginica'],
       [139, 6.0, 3.0, 4.8, 1.8, 'Iris-virginica'],
       [140, 6.9, 3.1, 5.4, 2.1, 'Iris-virginica'],
       [141, 6.7, 3.1, 5.6, 2.4, 'Iris-virginica'],
       [142, 6.9, 3.1, 5.1, 2.3, 'Iris-virginica'],
       [143, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [144, 6.8, 3.2, 5.9, 2.3, 'Iris-virginica'],
       [145, 6.7, 3.3, 5.7, 2.5, 'Iris-virginica'],
       [146, 6.7, 3.0, 5.2, 2.3, 'Iris-virginica'],
       [147, 6.3, 2.5, 5.0, 1.9, 'Iris-virginica'],
       [148, 6.5, 3.0, 5.2, 2.0, 'Iris-virginica'],
       [149, 6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [150, 5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)

In [124]:
csv1.sort_index(axis=0,ascending = False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
149,150,5.9,3.0,5.1,1.8,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
...,...,...,...,...,...,...
4,5,5.0,3.6,1.4,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
0,1,5.1,3.5,1.4,0.2,Iris-setosa

In [125]:
csv1["SepalLengthCm"][0] = 3.5
csv1

/tmp/ipykernel_1024/1813421347.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv1["SepalLengthCm"][0] = 3.5
/tmp/ipykernel_1024/1813421347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv1["SepalLengthCm"][0] = 3.5

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,3.5,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [126]:
csv1.loc[0,"SepalLengthCm"] = 5.1
csv1

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [127]:
csv1.loc[[2,3],["SepalLengthCm","SepalWidthCm"]]

   SepalLengthCm  SepalWidthCm
2            4.7           3.2
3            4.6           3.1

In [128]:
csv1.iloc[0,1]

np.float64(5.1)

In [129]:
csv1.drop("SepalLengthCm",axis=1)

      Id  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1           3.5            1.4           0.2     Iris-setosa
1      2           3.0            1.4           0.2     Iris-setosa
2      3           3.2            1.3           0.2     Iris-setosa
3      4           3.1            1.5           0.2     Iris-setosa
4      5           3.6            1.4           0.2     Iris-setosa
..   ...           ...            ...           ...             ...
145  146           3.0            5.2           2.3  Iris-virginica
146  147           2.5            5.0           1.9  Iris-virginica
147  148           3.0            5.2           2.0  Iris-virginica
148  149           3.4            5.4           2.3  Iris-virginica
149  150           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [130]:
csv1.drop(0,axis=0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

**Handling Missing Data**

**1. Replace**

In [131]:
csv1.replace(to_replace=1,value=22)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,22,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [132]:
csv2 = csv1.replace([1,2,3,4,5],np.nan)
csv2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.5,1.4,0.2,Iris-setosa
1,NaN,4.9,NaN,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,NaN,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,NaN,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,NaN,1.9,Iris-virginica
147,148.0,6.5,NaN,5.2,NaN,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

In [133]:
csv1.replace("[A-Za-z]","python",regex=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,pythonpythonpythonpython-pythonpythonpythonpyt...
1,2,4.9,3.0,1.4,0.2,pythonpythonpythonpython-pythonpythonpythonpyt...
2,3,4.7,3.2,1.3,0.2,pythonpythonpythonpython-pythonpythonpythonpyt...
3,4,4.6,3.1,1.5,0.2,pythonpythonpythonpython-pythonpythonpythonpyt...
4,5,5.0,3.6,1.4,0.2,pythonpythonpythonpython-pythonpythonpythonpyt...
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,pythonpythonpythonpython-pythonpythonpythonpyt...
146,147,6.3,2.5,5.0,1.9,pythonpythonpythonpython-pythonpythonpythonpyt...
147,148,6.5,3.0,5.2,2.0,pythonpythonpythonpython-pythonpythonpythonpyt...
148,149,6.2,3.4,5.4,2.3,pythonpythonpythonpython-pythonpythonpythonpyt...
149,150,5.9,3.0,5.1,1.8,pythonpythonpythonpython-pythonpythonpythonpyt...

In [134]:
csv1.replace({"Species":'[A-Z]'},22,regex=True)

/tmp/ipykernel_1024/3387827895.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv1.replace({"Species":'[A-Z]'},22,regex=True)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2       22
1      2            4.9           3.0            1.4           0.2       22
2      3            4.7           3.2            1.3           0.2       22
3      4            4.6           3.1            1.5           0.2       22
4      5            5.0           3.6            1.4           0.2       22
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3       22
146  147            6.3           2.5            5.0           1.9       22
147  148            6.5           3.0            5.2           2.0       22
148  149            6.2           3.4            5.4           2.3       22
149  150            5.9           3.0            5.1           1.8       22

[150 rows x 6 columns]

In [135]:
csv1.replace(4.9,method="ffill")

/tmp/ipykernel_1024/4171984265.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv1.replace(4.9,method="ffill")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,5.1,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [136]:
csv1.replace(4.9,method="bfill")

/tmp/ipykernel_1024/1474143949.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv1.replace(4.9,method="bfill")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.7,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [137]:
csv1.replace(4.9,method="bfill",limit=1)

/tmp/ipykernel_1024/2728578250.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv1.replace(4.9,method="bfill",limit=1)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.7,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

*Inplace parameter can be used to permanently chamge the csv.*

**2. Interpolate**

In [138]:
csv2.interpolate(method="linear",axis = 0)

/tmp/ipykernel_1024/2873674520.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv2.interpolate(method="linear",axis = 0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.50,1.4,0.2,Iris-setosa
1,NaN,4.9,3.35,1.4,0.2,Iris-setosa
2,NaN,4.7,3.20,1.3,0.2,Iris-setosa
3,NaN,4.6,3.10,1.5,0.2,Iris-setosa
4,NaN,5.0,3.60,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,2.90,5.2,2.3,Iris-virginica
146,147.0,6.3,2.50,5.2,1.9,Iris-virginica
147,148.0,6.5,2.95,5.2,2.1,Iris-virginica
148,149.0,6.2,3.40,5.4,2.3,Iris-virginica
149,150.0,5.9,3.40,5.1,1.8,Iris-virginica

In [139]:
csv2.interpolate(limit_direction="backward",limit = 2)

/tmp/ipykernel_1024/1623178454.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv2.interpolate(limit_direction="backward",limit = 2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.50,1.4,0.2,Iris-setosa
1,NaN,4.9,3.35,1.4,0.2,Iris-setosa
2,NaN,4.7,3.20,1.3,0.2,Iris-setosa
3,6.0,4.6,3.10,1.5,0.2,Iris-setosa
4,6.0,5.0,3.60,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,2.90,5.2,2.3,Iris-virginica
146,147.0,6.3,2.50,5.2,1.9,Iris-virginica
147,148.0,6.5,2.95,5.2,2.1,Iris-virginica
148,149.0,6.2,3.40,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

In [140]:
csv2.interpolate(limit_area="inside")

/tmp/ipykernel_1024/1550256996.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv2.interpolate(limit_area="inside")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.50,1.4,0.2,Iris-setosa
1,NaN,4.9,3.35,1.4,0.2,Iris-setosa
2,NaN,4.7,3.20,1.3,0.2,Iris-setosa
3,NaN,4.6,3.10,1.5,0.2,Iris-setosa
4,NaN,5.0,3.60,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,2.90,5.2,2.3,Iris-virginica
146,147.0,6.3,2.50,5.2,1.9,Iris-virginica
147,148.0,6.5,2.95,5.2,2.1,Iris-virginica
148,149.0,6.2,3.40,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

**3. Dropna & Fillna**

In [141]:
csv2.dropna()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5,6.0,5.4,3.9,1.7,0.4,Iris-setosa
6,7.0,4.6,3.4,1.4,0.3,Iris-setosa
8,9.0,4.4,2.9,1.4,0.2,Iris-setosa
9,10.0,4.9,3.1,1.5,0.1,Iris-setosa
10,11.0,5.4,3.7,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
141,142.0,6.9,3.1,5.1,2.3,Iris-virginica
142,143.0,5.8,2.7,5.1,1.9,Iris-virginica
143,144.0,6.8,3.2,5.9,2.3,Iris-virginica
144,145.0,6.7,3.3,5.7,2.5,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica

In [142]:
csv2.dropna(axis=1)

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [143]:
csv2.dropna(how="any")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5,6.0,5.4,3.9,1.7,0.4,Iris-setosa
6,7.0,4.6,3.4,1.4,0.3,Iris-setosa
8,9.0,4.4,2.9,1.4,0.2,Iris-setosa
9,10.0,4.9,3.1,1.5,0.1,Iris-setosa
10,11.0,5.4,3.7,1.5,0.2,Iris-setosa
...,...,...,...,...,...,...
141,142.0,6.9,3.1,5.1,2.3,Iris-virginica
142,143.0,5.8,2.7,5.1,1.9,Iris-virginica
143,144.0,6.8,3.2,5.9,2.3,Iris-virginica
144,145.0,6.7,3.3,5.7,2.5,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica

In [144]:
csv2.dropna(subset = ["SepalLengthCm"])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.5,1.4,0.2,Iris-setosa
1,NaN,4.9,NaN,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
5,6.0,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,NaN,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,NaN,1.9,Iris-virginica
147,148.0,6.5,NaN,5.2,NaN,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

In [145]:
csv2.dropna(thresh=1)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.5,1.4,0.2,Iris-setosa
1,NaN,4.9,NaN,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,NaN,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,NaN,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,NaN,1.9,Iris-virginica
147,148.0,6.5,NaN,5.2,NaN,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

In [146]:
csv2.fillna("python")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,python,5.1,3.5,1.4,0.2,Iris-setosa
1,python,4.9,python,1.4,0.2,Iris-setosa
2,python,4.7,3.2,1.3,0.2,Iris-setosa
3,python,4.6,3.1,1.5,0.2,Iris-setosa
4,python,python,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,python,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,python,1.9,Iris-virginica
147,148.0,6.5,python,5.2,python,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,python,5.1,1.8,Iris-virginica

In [147]:
csv2.fillna({"SepalLengthCm":"python","SepalWidthCm":"55"})

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.5,1.4,0.2,Iris-setosa
1,NaN,4.9,55,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,NaN,4.6,3.1,1.5,0.2,Iris-setosa
4,NaN,python,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,55,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,NaN,1.9,Iris-virginica
147,148.0,6.5,55,5.2,NaN,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,55,5.1,1.8,Iris-virginica

In [148]:
csv2.fillna(method="bfill")

/tmp/ipykernel_1024/2346906966.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv2.fillna(method="bfill")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,6.0,5.1,3.5,1.4,0.2,Iris-setosa
1,6.0,4.9,3.2,1.4,0.2,Iris-setosa
2,6.0,4.7,3.2,1.3,0.2,Iris-setosa
3,6.0,4.6,3.1,1.5,0.2,Iris-setosa
4,6.0,5.4,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,2.5,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.2,1.9,Iris-virginica
147,148.0,6.5,3.4,5.2,2.3,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

In [149]:
csv2.fillna(method="bfill",axis=0,limit=2)

/tmp/ipykernel_1024/4252471613.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv2.fillna(method="bfill",axis=0,limit=2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,NaN,5.1,3.5,1.4,0.2,Iris-setosa
1,NaN,4.9,3.2,1.4,0.2,Iris-setosa
2,NaN,4.7,3.2,1.3,0.2,Iris-setosa
3,6.0,4.6,3.1,1.5,0.2,Iris-setosa
4,6.0,5.4,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146.0,6.7,2.5,5.2,2.3,Iris-virginica
146,147.0,6.3,2.5,5.2,1.9,Iris-virginica
147,148.0,6.5,3.4,5.2,2.3,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,NaN,5.1,1.8,Iris-virginica

*Inplace can be true or false to permanently change*

***Merge & Concat***

In [150]:
var_1=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var_2=pd.DataFrame({"A":[1,2,3,5],"C":[15,16,17,18]})
pd.merge(var_1,var_2,on="A")#only works on commom data

   A  B   C
0  1  5  15
1  2  6  16
2  3  7  17

In [151]:
var_1=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var_2=pd.DataFrame({"A":[1,2,3,5],"C":[15,16,17,18]})
pd.merge(var_1,var_2,how = "left")

   A  B     C
0  1  5  15.0
1  2  6  16.0
2  3  7  17.0
3  4  8   NaN

In [152]:
pd.merge(var_1,var_2,how = "right")

   A    B   C
0  1  5.0  15
1  2  6.0  16
2  3  7.0  17
3  5  NaN  18

In [153]:
pd.merge(var_1,var_2,how = "outer",indicator=True)

   A    B     C      _merge
0  1  5.0  15.0        both
1  2  6.0  16.0        both
2  3  7.0  17.0        both
3  4  8.0   NaN   left_only
4  5  NaN  18.0  right_only

In [154]:
var_3=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var_4=pd.DataFrame({"A":[1,2,3,5],"B":[15,16,17,18]})
pd.merge(var_3,var_4,left_index=True,right_index=True,suffixes=("name","class"))

   Aname  Bname  Aclass  Bclass
0      1      5       1      15
1      2      6       2      16
2      3      7       3      17
3      4      8       5      18

In [155]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,12,13,14])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    12
2    13
3    14
dtype: int64

In [180]:
var_1=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var_2=pd.DataFrame({"A":[1,2],"C":[15,16]})
pd.concat([var_1,var_2],axis = 1,join="inner")

   A  B  A   C
0  1  5  1  15
1  2  6  2  16

In [157]:
var_1=pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var_2=pd.DataFrame({"A":[1,2,3,5],"C":[15,16,17,18]})
pd.concat([var_1,var_2],keys=["x","y"],axis = 1)

   x     y
   A  B  A   C
0  1  5  1  15
1  2  6  2  16
2  3  7  3  17
3  4  8  5  18

***Group By***

In [158]:
varr = pd.DataFrame({"Name":["A","B","C","D","A","B","A","B","A","C","C","D"],
                     "S_1":[12,13,14,12,13,14,15,23,25,16,10,34],
                     "S_2":[23,24,25,26,27,28,29,30,25,34,35,56]})
varr

   Name  S_1  S_2
0     A   12   23
1     B   13   24
2     C   14   25
3     D   12   26
4     A   13   27
5     B   14   28
6     A   15   29
7     B   23   30
8     A   25   25
9     C   16   34
10    C   10   35
11    D   34   56

In [159]:
varr_1 = varr.groupby("Name")
varr_1

In [160]:
for x,y in varr_1:
  print(x)
  print(y)
  print( )

A
  Name  S_1  S_2
0    A   12   23
4    A   13   27
6    A   15   29
8    A   25   25

B
  Name  S_1  S_2
1    B   13   24
5    B   14   28
7    B   23   30

C
   Name  S_1  S_2
2     C   14   25
9     C   16   34
10    C   10   35

D
   Name  S_1  S_2
3     D   12   26
11    D   34   56

In [161]:
varr_1.get_group("A")

  Name  S_1  S_2
0    A   12   23
4    A   13   27
6    A   15   29
8    A   25   25

In [162]:
varr_1.min()

      S_1  S_2
Name
A      12   23
B      13   24
C      10   25
D      12   26

In [163]:
varr_1.max()

      S_1  S_2
Name
A      25   29
B      23   30
C      16   35
D      34   56

In [164]:
varr_1.mean()

            S_1        S_2
Name
A     16.250000  26.000000
B     16.666667  27.333333
C     13.333333  31.333333
D     23.000000  41.000000

In [165]:
li = list(varr_1)
li

[('A',
    Name  S_1  S_2
  0    A   12   23
  4    A   13   27
  6    A   15   29
  8    A   25   25),
 ('B',
    Name  S_1  S_2
  1    B   13   24
  5    B   14   28
  7    B   23   30),
 ('C',
     Name  S_1  S_2
  2     C   14   25
  9     C   16   34
  10    C   10   35),
 ('D',
     Name  S_1  S_2
  3     D   12   26
  11    D   34   56)]

**Join**

In [166]:
import pandas as pd
varrr1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
varrr2 = pd.DataFrame({"c":[10,20,30,40],"D":[11,22,33,44]})
varrr1.join(varrr2)

   A   B   c   D
0  1  11  10  11
1  2  12  20  22
2  3  13  30  33
3  4  14  40  44

In [167]:
varrr1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
varrr2 = pd.DataFrame({"C":[10,20],"D":[11,22]})
varrr1.join(varrr2)

   A   B     C     D
0  1  11  10.0  11.0
1  2  12  20.0  22.0
2  3  13   NaN   NaN
3  4  14   NaN   NaN

In [168]:
varrr2.join(varrr1)

    C   D  A   B
0  10  11  1  11
1  20  22  2  12

In [169]:
varrr2.join(varrr1,how = "left")

    C   D  A   B
0  10  11  1  11
1  20  22  2  12

In [170]:
varrr2.join(varrr1,how = "right")

      C     D  A   B
0  10.0  11.0  1  11
1  20.0  22.0  2  12
2   NaN   NaN  3  13
3   NaN   NaN  4  14

In [171]:
varrr2 = pd.DataFrame({"B":[10,20],"D":[11,22]})
varrr2.join(varrr1,how = "outer",lsuffix="_1",rsuffix="_2")

    B_1     D  A  B_2
0  10.0  11.0  1   11
1  20.0  22.0  2   12
2   NaN   NaN  3   13
3   NaN   NaN  4   14

**Melt()**

In [172]:
va=pd.DataFrame({"Day":[1,2,3,4,5,6],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})
va

   Day  eng  math
0    1   10    17
1    2   12    18
2    3   14    19
3    4   15    13
4    5   16    14
5    6   12    16

In [173]:
pd.melt(va)

   variable  value
0       Day      1
1       Day      2
2       Day      3
3       Day      4
4       Day      5
5       Day      6
6       eng     10
7       eng     12
8       eng     14
9       eng     15
10      eng     16
11      eng     12
12     math     17
13     math     18
14     math     19
15     math     13
16     math     14
17     math     16

In [174]:
pd.melt(va,id_vars=['Day'],var_name="sub",value_name="marks")

    Day   sub  marks
0     1   eng     10
1     2   eng     12
2     3   eng     14
3     4   eng     15
4     5   eng     16
5     6   eng     12
6     1  math     17
7     2  math     18
8     3  math     19
9     4  math     13
10    5  math     14
11    6  math     16

**Pivot**

In [175]:
va=pd.DataFrame({"Day":[1,2,3,4,5,6],"st_name":["a","b","c","a","b","c"],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})
va

   Day st_name  eng  math
0    1       a   10    17
1    2       b   12    18
2    3       c   14    19
3    4       a   15    13
4    5       b   16    14
5    6       c   12    16

In [176]:
va.pivot(index="Day",columns="st_name")

          eng              math
st_name     a     b     c     a     b     c
Day
1        10.0   NaN   NaN  17.0   NaN   NaN
2         NaN  12.0   NaN   NaN  18.0   NaN
3         NaN   NaN  14.0   NaN   NaN  19.0
4        15.0   NaN   NaN  13.0   NaN   NaN
5         NaN  16.0   NaN   NaN  14.0   NaN
6         NaN   NaN  12.0   NaN   NaN  16.0

In [177]:
va.pivot(index="Day",columns="st_name",values="eng")

st_name     a     b     c
Day
1        10.0   NaN   NaN
2         NaN  12.0   NaN
3         NaN   NaN  14.0
4        15.0   NaN   NaN
5         NaN  16.0   NaN
6         NaN   NaN  12.0

In [178]:
va=pd.DataFrame({"Day":[1,1,1,1,2,2],"st_name":["a","b","a","a","b","b"],"eng":[10,12,14,15,16,12],"math":[17,18,19,13,14,16]})
va.pivot_table(index="Day",columns="st_name",aggfunc="sum",margins="True")

          eng            math
st_name     a     b All     a     b All
Day
1        39.0  12.0  51  49.0  18.0  67
2         NaN  28.0  28   NaN  30.0  30
All      39.0  40.0  79  49.0  48.0  97